### PR TITLE
Update config.sh.sample

### PR DESCRIPTION
**Pull request by arturmoreira**
Update Outline version to 0.66.0

### CODE REVIEW

**Comment by arturmoreira** [comment]
Hi. Believe it or not, this is my first pull request **ever**!
I don't know if I've done everything correctly but, if I did, I just wanted to say that I updated Outline version to the latest (0.66.0) and tried to do all the process from beginning to end: everything appeared to have worked correctly.

**Comment by arturmoreira** [comment]
Sorry to bother you but, is there any reason why you closed the pull request without accepting it or not commenting on it?
I don't mean in any way to sound rude. I'm just asking because, as I said, I'm not very experienced in Git so I'd like to learn in case I've done anything wrong.
Thanks.

**Comment by vicalloy** [comment]
1. This pull request changed git  address in README.md
2. The default value of `OUTLINE_VERSION` is a validated outline version. If your want newset outline, you can change it to `latest` and rollback to default version if `latest` is not working.

**Comment by arturmoreira** [comment]
Thank you very much for taking the time to answer me and explain me the details I asked for. Keep up the good work!

**Pull request closed without merging**
